home/urls.py
from . import views
from django.urls import path

app_name = "app"

urlpatterns = [
    path("", views.home),
    path("dashboard", views.dashboard),
    path("orders", views.orders, name="orders"),
    path("adminview", views.Admin, name="admin"),
    path("gold", views.Gold, name="gold"),
    path("new_order", views.newOrder, name="new_order"),
    path("edit_order/<str:id>", views.editOrder, name="edit_order"),
     path("edit_table/<str:id>", views.editTable, name="edit_table"),
    path("delete_order/<str:id>", views.deleteOrder, name="delete_order"),
    path("filterbyshop", views.filterByShop, name="filterbyshop"),
    path("assign_to_manufacturer", views.assign_to_manufacturer, name="assign_to_manufacturer"),
    path("completed_orders", views.completedOrders, name="completed_orders"),
    path("markascomplete/<str:id>", views.markAsComplete, name="markascomplete"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("editshop/<str:shop_id>", views.editshop, name="editshop"),
    path('item/<int:item_id>/add_chat_note/', views.add_chat_note, name='add_chat_note'),
     path('export-to-excel/', views.export_items_to_excel, name='export_to_excel'),
    ]

ordermgmt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls'),name='user')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from . import views
from django.urls import path,include

app_name= 'user'

urlpatterns = [
    path('login',views.signin,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('add_user',views.add_user,name='add_user'),
    path('edit_user/<int:user_id>',views.edit_user,name='edit_user'),
    path('remove_user/<int:user_id>',views.remove_user,name='remove_user'),
    
]

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from user.models import User
from .models import Item, Topup, ChatNote

from django.contrib import messages
from django.db.models import Sum, Count, Q, FloatField
from django.db.models import F, Func, Value, Q, Case, When
from django.db.models.functions import Cast
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def home(request):
    return render(request, "home/index.html")


@login_required
def orders(request):
    if request.user.user_type == "manufacturer":
        orders = Item.objects.filter(assigned_to=request.user, completed=False).order_by('id')
    elif request.user.user_type == "shop":
        orders = Item.objects.filter(shop=request.user).order_by('id')
    else:
        orders = Item.objects.filter(completed=False).order_by('id')

    p_customers = Paginator(orders, 10)
    page_number = request.GET.get("page")
    try:
        page_obj = p_customers.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p_customers.page(1)
    except EmptyPage:
        page_obj = p_customers.page(p_customers.num_pages)

    shops = User.objects.filter(user_type="shop")
    mans = User.objects.filter(user_type="manufacturer")
    return render(
        request, "home/orders.html", {"items": page_obj, "shops": shops, "mans": mans}
    )


@login_required
def Admin(request):
    if request.GET.get("page") == "edit":
        user_id = request.GET.get("id")
        user = User.objects.get(pk=user_id)
        return render(request, "home/admin.html", {"user": user})
    users = User.objects.filter(is_superuser=False).values
    return render(request, "home/admin.html", {"users": users})

@login_required
def newOrder(request):
    if request.method == "POST":
        try:
            order_data = {
                'stone_status': request.POST.get('stone_status'),
                'order_id': request.POST.get('order_id'),
                'order_id_2': request.POST.get('order_id_2'),
                'status': request.POST.get('status'),
                'order_date': request.POST.get('order_date'),
                'admin_photo': request.FILES.get('admin_photo'),
                'manufacturer_photo': request.FILES.get('manufacturer_photo'),
                'title': request.POST.get('title'),
                'quantity': request.POST.get('quantity'),
                'material': request.POST.get('material'),
                'color': request.POST.get('color'),
                'size': request.POST.get('size'),
                'personalization': request.POST.get('personalization'),
                'main_stone1': request.POST.get('main_stone1'),
                'main_stone2': request.POST.get('main_stone2'),
                'main_stone3': request.POST.get('main_stone3'),
                'main_stone4': request.POST.get('main_stone4', 0.0),
                'side_stone1': request.POST.get('side_stone1'),
                'side_stone2': request.POST.get('side_stone2'),
                'side_stone3': request.POST.get('side_stone3'),
                'side_stone4': request.POST.get('side_stone4', 0.0),
                'material_used1': request.POST.get('material_used1'),
                'material_used2': request.POST.get('material_used2'),
                'material_used3': request.POST.get('material_used3'),
                'material_used4': request.POST.get('material_used4', 0.0),
                'labour1': request.POST.get('labour1'),
                'labour2': request.POST.get('labour2'),
                'labour3': request.POST.get('labour3', 0.0),
                'delivery_cost': request.POST.get('delivery_cost', 0),
                'packaging_cost': request.POST.get('packaging_cost', 0),
                'total_cost': request.POST.get('total_cost', 0),
                'customer_name': request.POST.get('customer_name'),
                'customer_email': request.POST.get('customer_email'),
                'customer_mobile': request.POST.get('customer_mobile'),
                'tracking_id': request.POST.get('tracking_id'),
                'shipping_method': request.POST.get('shipping_method'),
                'country': request.POST.get('country'),
                'address': request.POST.get('address'),
            }
            try:
                shop_id = request.POST.get('shop_id')
                shop = User.objects.get(pk=shop_id, user_type="shop")
                order_data['shop'] = shop
            except Exception as e:
                messages.error(request, f"An error occurred while getting the shop {e}")
                return render(request, "home/new_order.html")
            if request.POST.get('completed') == 'on':
                order_data['completed'] = True
            else:
                order_data['completed'] = False
            #print(request.POST)
            if(request.POST["order_date"]):
                order_data["order_date"] = request.POST["order_date"]
                
            if(request.POST["last_date"]):
                order_data["last_date"] = request.POST["last_date"]
                #print("sdfdf")
            if(request.POST["original_delivery_date"]):
                order_data["original_delivery_date"] = request.POST["original_delivery_date"]
            
            Item.objects.create(**order_data)
            messages.success(request, "Order created successfully")
            return redirect('/orders')
        except Exception as e:
            messages.error(request, f"An error occurred while creating the order {e}")
            return render(request, "home/new_order.html")
    shops = User.objects.filter(user_type="shop")
    return render(request, "home/new_order.html", {"shops": shops})

@login_required
def editOrder(request, id):
    order = Item.objects.get(pk=id)
    shops = User.objects.filter(user_type="shop")
    if request.method == 'POST':
        try:
            order.order_id = request.POST.get('order_id', order.getOrderID())
            order.order_id_2 = request.POST.get('order_id_2', order.get2OrderID())
            order.status = request.POST.get('status', order.getStatus())
            order.order_date = request.POST.get('order_date', order.getOrderDate())
            if request.FILES.get('admin_photo'):
                order.admin_photo = request.FILES.get('admin_photo')
            if request.FILES.get('manufacturer_photo'):
                order.manufacturer_photo = request.FILES.get('manufacturer_photo')
            order.title = request.POST.get('title', order.getTitle())
            order.quantity = request.POST.get('quantity', order.getQuantity())
            order.material = request.POST.get('material', order.getMaterial())
            order.color = request.POST.get('color', order.getColor())
            order.size = request.POST.get('size', order.getSize())
            order.personalization = request.POST.get('personalization', order.getPersonalization())
            if request.POST.get('last_date'):
                order.last_date = request.POST.get('last_date', order.getLastDate())
            order.stone_status = request.POST.get('stone_status') if request.POST.get('stone_status') not in ["None", None] else order.stone_status
            order.main_stone1 = request.POST.get('main_stone1') if request.POST.get('main_stone1') not in ["None", None] else order.main_stone1
            order.main_stone2 = request.POST.get('main_stone2') if request.POST.get('main_stone2') not in ["None", None] else order.main_stone2
            order.main_stone3 = request.POST.get('main_stone3') if request.POST.get('main_stone3') not in ["None", None] else order.main_stone3
            order.main_stone4 = request.POST.get('main_stone4') if request.POST.get('main_stone3') not in ["None", None] else order.main_stone4
            order.side_stone1 = request.POST.get('side_stone1') if request.POST.get('side_stone1') not in ["None", None] else order.side_stone1
            order.side_stone2 = request.POST.get('side_stone2') if request.POST.get('side_stone1') not in ["None", None] else order.side_stone2
            order.side_stone3 = request.POST.get('side_stone3') if request.POST.get('side_stone1') not in ["None", None] else order.side_stone3
            order.side_stone4 = request.POST.get('side_stone4') if request.POST.get('side_stone1') not in ["None", None] else order.side_stone4
            order.material_used1 = request.POST.get('material_used1') if request.POST.get('material_used1') not in ["None", None] else order.material_used1
            order.material_used2 = request.POST.get('material_used2') if request.POST.get('material_used1') not in ["None", None] else order.material_used2
            order.material_used3 = request.POST.get('material_used3') if request.POST.get('material_used1') not in ["None", None] else order.material_used3
            order.material_used4 = request.POST.get('material_used4') if request.POST.get('material_used1') not in ["None", None] else order.material_used4
            order.labour1 = request.POST.get('labour1') if request.POST.get('labour1') not in ["None", None] else order.labour1
            order.labour2 = request.POST.get('labour2') if request.POST.get('labour1') not in ["None", None] else order.labour2
            order.labour3 = request.POST.get('labour3') if request.POST.get('labour1') not in ["None", None] else order.labour3
            order.delivery_cost = request.POST.get('delivery_cost', order.getDeliveryCost())
            order.packaging_cost = request.POST.get('packaging_cost', order.getPackagingCost())
            order.total_cost = float(order.getMainStone4()) + float(order.getSideStone4()) + float(order.getMaterialUsed4()) + float(order.getLabour3()) + float(order.getPackagingCost()) + float(order.getDeliveryCost())
            if request.POST.get('original_delivery_date'):

templates/home/admin.html
{% extends "base.html" %}
{% load static %}
<style>
  .table>:not(caption)>*>*{
  padding:5px;
}
a{
      text-decoration: none;
      color: black;
  
}

@media (max-width:1200px){
tbody, tbody tr th{
    font-size: 9px !important;
}
.btn{
  margin-bottom: 10px !important;
}
}

</style>

{% block content %}

<div class="container-fluid">
  <!-- Row 1 -->
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech">
      <div class="card w-100">
        <div class="card-body">
          
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
          <div class="d-sm-flex d-block align-items-center justify-content-between mb-9">
            
            <div class="mb-3 mb-sm-0">
             <a href="{% url "app:admin" %}"> <h5 class="card-title fw-semibold text-primary text-decoration-underline">User Management</h5></a>
            </div>
            <div>
              <a href="?page=add" class="btn btn-primary">Add User</a>
            </div>
          </div>
          <div style="overflow-x: auto;">
            <!-- User Table -->
            
            {% if request.GET.page == 'add' %}
              <h3>Add User</h3>
                        <!-- User Addition Form -->
                        <form id="addUserForm" method="post" action="{% url "user:add_user" %}">
                          {% csrf_token %}
                          <div class="mb-3">
                            <label for="first_name" class="form-label">First Name</label>
                            <input type="text" class="form-control" id="first_name" name="first_name" required>
                          </div>
                          <div class="mb-3">
                            <label for="last_name" class="form-label">Last Name</label>
                            <input type="text" class="form-control" id="last_name" name="last_name" required>
                          </div>
                          <div class="mb-3">
                            <label for="email" class="form-label">Email address</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                          </div>
                          <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                          </div>
                          <div class="mb-3">
                            <label class="form-label" for="user_type">User Type</label>
                            <select class="form-select" name="user_type" id="user_type">
                              <option value="employee">Employee</option>
                              <option value="manufacturer">Manufacturer</option>
                              <option value="admin">Admin</option>
                              <option value="shop">Shop</option>
                              <option value="designer">Designer</option>
                            </select>
                            
                          </div>
                          <button onclick="loadBtn()" type="submit" class="btn btn-primary">Add User</button>
                        </form>
                        <!-- End User Addition Form -->
                        {% elif request.GET.page == 'edit' %}
                        {% if user %}
                          <!-- User Edit Form -->
                          <button  class="mb-3 btn-outline-info btn">{{user.email}}</button>
                          <form id="editUserForm" method="post" action="{% url 'user:edit_user' user.id %}">
                            {% csrf_token %}
                            <div class="mb-3">
                              <label for="editEmail" class="form-label">Email address</label>
                              <input type="email" value={{user.email}} class="form-control" id="editEmail" name="email" required>
                            </div>
                            <div class="mb-3">
                              <label for="editPassword" class="form-label">Password</label>
                              <input type="password"   class="form-control" id="password" name="password" >
                            </div>
                            <div class="mb-3">
                              <label class="form-check-label" for="user_type">User Type</label>
                              <select class="form-select" name="user_type" id="user_type">
                                <option value="employee"  {% if user.user_type == "employee" %} selected {% endif %} >Employee</option>
                                <option value="manufacturer" {% if user.user_type == "manufacturer" %} selected {% endif %}>Manufacturer</option>
                                <option value="admin" {% if user.user_type == "admin" %} selected {% endif %}>Admin</option>
                                <option value="shop" {% if user.user_type == "shop" %} selected {% endif %}>Shop</option>
                                <option value="designer" {% if user.user_type == "designer" %} selected {% endif %}>Designer</option>
                              </select>
                             
                            </div>
                            <button type="submit" class="btn btn-primary">Update User</button>
                          </form>
                      <!-- End User Edit Form -->
                      {% else %}
                          <p>User not found.</p>
                        {% endif %}
                      {% else %}
                <table class="table" style="overflow-x: auto;">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Username</th>
                      <th>Email</th>
                      <th>User Type</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if users %}
                      {% for user in users %}
                        <tr>
                          <td>{{ user.id }}</td>
                          <td>{{ user.username }}</td>
                          <td>{{ user.email }}</td>
                          <td>{{ user.user_type }}</td>
                          <td>
                            <a href="#" class="edit-user-btn" data-user-id="{{ user.id }}">
                              <svg xmlns="http://www.w3.org/2000/svg" class="text-warning icon icon-tabler icon-tabler-pencil" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4" /><path d="M13.5 6.5l4 4" /></svg>
                            </a>
                            <a href="#" class="delete-user-btn" data-user-id="{{ user.id }}">
                              <svg xmlns="http://www.w3.org/2000/svg" class="text-danger icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 7l16 0" /><path d="M10 11l0 6" /><path d="M14 11l0 6" /><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" /><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" /></svg>
                            </a>
                          </td>
                        </tr>
                      {% endfor %}
                {% else %}
                  <tr class="text-center display-flex align-items-center justify-content-center">
                    <td colspan="9" class="text-center">No Users</td>
                  </tr>
                {% endif %}
              </tbody>
            </table>
              {% endif %}


          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const editButtons = document.querySelectorAll('.edit-user-btn');
    editButtons.forEach(button => {
      button.addEventListener('click', function (event) {
        event.preventDefault();
        const userId = button.getAttribute('data-user-id');
        window.location.href = `?page=edit&id=${userId}`;
      });
    });
  });
  document.addEventListener('DOMContentLoaded', function () {
    const editButtons = document.querySelectorAll('.edit-client-btn');
    editButtons.forEach(button => {
      button.addEventListener('click', function (event) {
        event.preventDefault();
        const clientId = button.getAttribute('data-client-id');
        window.location.href = `?page=edit_client&id=${clientId}`;
      });
    });
  });
  document.addEventListener('DOMContentLoaded', function () {
    const deleteButtons = document.querySelectorAll('.delete-user-btn');
    deleteButtons.forEach(button => {
      button.addEventListener('click', function (event) {
        event.preventDefault();
        const userId = button.getAttribute('data-user-id');
        const confirmDelete = confirm('Are you sure you want to delete this user?');

        if (confirmDelete) {
          // Redirect to the delete URL if the user confirms
          window.location.href = `user/remove_user/${userId}`;
        }
      });
    });
  });
  document.addEventListener('DOMContentLoaded', function () {
    const deleteButtons = document.querySelectorAll('.delete-client-btn');
    deleteButtons.forEach(button => {
      button.addEventListener('click', function (event) {
        event.preventDefault();
        const clientId = button.getAttribute('data-client-id');
        const confirmDelete = confirm('Are you sure you want to delete this client?');

        if (confirmDelete) {
          window.location.href = `remove_client/${clientId}`;
        }
      });
    });
  });
  function loadBtn(e){
    e.disabled = true
    e.innerHTML = 'Loading...'
    document.getElementById('addUserForm').submit()
  }
</script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
  $(document).ready(function() {
    $('.add-campaign-btn').on('click', function() {
      var clientId = $(this).data('client-id');
      $('#clientId').val(clientId);
    });
  });
</script>

  {% endblock content %}

templates/home/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<style>
  .table>:not(caption)>*>*{
  padding:5px;
}
a{
      text-decoration: none;
      color: black;
  
}

@media (max-width:1200px){
tbody, tbody tr th{
    font-size: 9px !important;
}
.btn{
  margin-bottom: 10px !important;
}
.table1 {
  width: 300px !important;
  overflow: auto !important;
}
}

</style>

{% endblock css %}

{% block content %}

<div class="container-fluid" style="max-width:1500px">
  <!-- Row 1 -->
  <div class="row">
    <div class="col-lg-12 d-flex align-items-strech w-100">
      <div class="card w-100">
        <div class="card-body">
          
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
          <div class="d-sm-flex d-block align-items-center justify-content-between mb-9">
            <div class="mb-3 mb-sm-0">
             <a href="/dashboard"> <h5 class="card-title fw-semibold text-primary text-decoration-underline">Dashboard</h5></a>
            </div>
            <div>
              <button type="button" class="btn btn-primary">Total Orders : {{total_orders}}</button>
            </div>
            <div>
              <button type="button" class="btn btn-primary">Open Orders : {{new_orders}}</button>
            </div>
            <div>
              <button type="button" class="btn btn-primary">Revenue : {{total_revenue}}</button>
            </div>
            
          </div>
          <div>
<div class="table1">
<table class="table" >
  <thead>
<tr>
<th>
Shop Name
</th>
<th onclick="sortTable(0)">
Total Orders <span id="arrow0"></span>
</th>
<th>
New Orders
</th>
<th onclick="sortTable(1)">
Completed Orders <span id="arrow1"></span>
</th>
<th >
Total Cost <span id="arrow3"></span>
</th>
<th >
Revenue <span id="arrow3"></span>
</th>
</tr>
</thead>

  <tbody id="myTable">
    {% if shop_details %}
    {% for shop in shop_details %}

      <tr>
      
        
        <td class="text-underlined" style="width: 20%;"><a href="{% url "app:editshop" shop.shop.id %}">{{ shop.shop.first_name }} {{shop.shop.last_name}} </a></td>
        <td style="width: 20%;">{{ shop.total_orders}}</td>
        <td style="width: 20%;">{{ shop.new_orders }}</td>
        <td style="width: 20%;">{{ shop.completed_orders }}</td>
        <td style="width: 20%;">{{ shop.total_cost }}</td>
        <td style="width: 20%;">{{ shop.revenue }}</td>
      </tr>
      {% endfor %}
      {% endif %}
  </tbody>
</table>
</div>


</div>
</div>
</div>
</div>
</div>
</div>

  {% endblock content %}

  {% block js %}
  {% endblock js %}

templates/home/editshop.html
{% extends "base.html" %}
<style>
  .table>:not(caption)>*>*{
  padding:5px;
}
a{
      text-decoration: none;
      color: black;
  
}

@media (max-width:1200px){
tbody, tbody tr th{
    font-size: 9px !important;
}
.btn{
  margin-bottom: 10px !important;
}
}

</style>
{% block content %}
<div class="container-fluid" style="max-width:1500px">
    <!-- Row 1 -->
    <div class="row">
      <div class="col-lg-12 d-flex align-items-strech w-100">
        <div class="card w-100">
          <div class="card-body">
            
{% if shop %}
  <h3>Update Revenue</h3>
  <form id="editshop" method="post" enctype="multipart/form-data" action="{% url 'app:editshop' shop.id %}">
    {% csrf_token %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if request.user.is_superuser %}
        <div class="mb-3">
            <label for="revenue" class="form-label">Revenue</label>
            <input type="text" class="form-control" id="revenue" name="revenue" value="{{ revenue }}" required>
        </div>
        {% endif %}
        
    <button type="submit" class="btn btn-primary">Update Order</button>
</form>
{% else %}
  <p>Shop not found.</p>
{% endif %}

</div>
</div>
</div>
{% endblock content %}

templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/js/tabler.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tabler-ui/dist/css/tabler.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    

<link rel="shortcut icon" href={% static "assets/img/logo.png" %} type="image/x-icon">

    <title>DNA Exports</title>
    <style>

        body::before {
            content: '';
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-image:url('{% static "assets/img/hero.avif" %}');
            background-size: cover;
            filter: blur(5px); /* Adjust the blur value as needed */
            z-index: -1;
            opacity: 0.9; /* Adjust the opacity value as needed */
          }
        
          body {
            color: white; /* Text color on top of the background image */
          }
          html, body {
            height: 100%;
            margin: 0;
        }
        
        body {
            display: flex;
            flex-direction: column;
        }
        
        .container {
            flex: 1;
        }
        
        
        .container-content {
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 80vh; 
        }

        .navbar {
          color: #fff; /* Text color */
          background-color:#fff;
      }
      .navbar-brand {
          font-size: 24px;
          font-weight: bold;
      }
      
        footer {
          background-color: #343a40; /* Footer background color */
          color: white; /* Footer text color */
          padding: 20px;
          margin-top: auto;
        }
      
        footer a {
          color: white; /* Footer link color */
          margin-right: 10px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-white-700">
        <div class="container">
            <a class="navbar-brand text-primary" href="/">DNA Exports</a>
            {% if user.is_authenticated %}
            <a class="nav-link text-azure" href="{% url "user:logout" %}"><button class="btn btn-primary">Sign out</button></a>
            {% else %}
            <a class="nav-link text-azure" href="{% url "user:login" %}"><button class="btn btn-primary">Sign In</button></a>
            {% endif %}
        </div>
    </nav>
    {% for message in messages %}
          <div class="container p-0" style="width:350px">
            <div class="alert {{ message.tags }} alert-dismissible m-0 text-center" role="alert" >
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="True">&times;</span>
              </button>
             {{ message }}
            </div>
          </div>
          {% endfor %}
   
        <div class="container-content">
          
            <div class="text-center">
                <h1>Welcome to DNA Exports</h1>
                <p>This is your personalized CRM solution for efficient business management.</p>
                <a href="/orders" class="btn btn-primary">Get Started</a>
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2024 DNA Exports</p>
            </div>
            <div class="col-md-6 text-md-end">
              <a href="#">Privacy Policy</a>
              <a href="#">Terms of Service</a>
              <!-- Add more footer links as needed -->
            </div>
          </div>
        </div>
      </footer>
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{% static "libs/jquery/dist/jquery.min.js" %}"></script>
    <script src="{% static "libs/bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/tabler@1.1/dist/js/tabler.min.js"></script>
</body>
</html>