home/urls.py
from . import views
from django.urls import path

app_name = "app"

urlpatterns = [
    path("", views.home),
    path("dashboard", views.dashboard),
    path("orders", views.orders, name="orders"),
    path("adminview", views.Admin, name="admin"),
    path("gold", views.Gold, name="gold"),
    path("new_order", views.newOrder, name="new_order"),
    path("edit_order/<str:id>", views.editOrder, name="edit_order"),
     path("edit_table/<str:id>", views.editTable, name="edit_table"),
    path("delete_order/<str:id>", views.deleteOrder, name="delete_order"),
    path("filterbyshop", views.filterByShop, name="filterbyshop"),
    path("assign_to_manufacturer", views.assign_to_manufacturer, name="assign_to_manufacturer"),
    path("completed_orders", views.completedOrders, name="completed_orders"),
    path("markascomplete/<str:id>", views.markAsComplete, name="markascomplete"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("editshop/<str:shop_id>", views.editshop, name="editshop"),
    path('item/<int:item_id>/add_chat_note/', views.add_chat_note, name='add_chat_note'),
     path('export-to-excel/', views.export_items_to_excel, name='export_to_excel'),
    ]

ordermgmt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('user/',include('user.urls'),name='user')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from . import views
from django.urls import path,include

app_name= 'user'

urlpatterns = [
    path('login',views.signin,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('add_user',views.add_user,name='add_user'),
    path('edit_user/<int:user_id>',views.edit_user,name='edit_user'),
    path('remove_user/<int:user_id>',views.remove_user,name='remove_user'),
    
]

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DNA Exports</title>
  <link rel="stylesheet" href="{% static "css/comboTreeStyle.css" %}" />
  <link rel="shortcut icon" type="image/png" href={% static "images/logos/favicon.png" %} />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href={% static "css/styles.min.css" %} />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
  <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">

  {% block css %}
  {% endblock %}
</head>

<body>
  <!--  Body Wrapper -->
  <div class="page-wrapper"  id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed">
    <!-- Sidebar Start -->
    <aside class="left-sidebar">
      <!-- Sidebar scroll-->
      <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
          <a href="/dashboard" class="text-nowrap logo-img">
            {% comment %} <img src="{% static "images/logos/dark-logo.svg" %}" width="180" alt="" /> {% endcomment %}
            <h3>DNA Exports</h3>
          </a>
          <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
            <i class="ti ti-x fs-8"></i>
          </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
          <ul id="sidebarnav">
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Home</span>
            </li>
            {% if request.user.is_superuser %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="/dashboard" aria-expanded="false">
                <span>
                  <i class="ti ti-layout-dashboard"></i>
                </span>
                <span class="hide-menu">Dashboard</span>
              </a>
            </li>
            {% endif %}
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">Your Tabs</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url "app:orders" %}" aria-expanded="false">
                <span>
                  <i class="ti ti-article"></i>
                </span>
                <span class="hide-menu">Orders</span>
              </a>
            </li>
          
            {% if request.user.is_superuser %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url "app:admin" %}" aria-expanded="false">
                <span>
                  <i class="ti ti-users"></i>
                </span>
                <span class="hide-menu">Admin</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url "app:gold" %}" aria-expanded="false">
                <span>
                  <i class="ti ti-users"></i>
                </span>
                <span class="hide-menu">Gold</span>
              </a>
            </li>
            {% endif %}
            {% if request.user.finance %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url "app:finance" %}" aria-expanded="false">
                <span>
                  <i class="ti ti-cards"></i>
                </span>
                <span class="hide-menu">Finance</span>
              </a>
            </li>
            {% endif %}
            {% if request.user.hr %}
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url "app:hr" %}" aria-expanded="false">
                <span>
                  <i class="ti ti-file-description"></i>
                </span>
                <span class="hide-menu">HR</span>
              </a>
            </li>
            {% endif %}
            {% comment %} </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./ui-typography.html" aria-expanded="false">
                <span>
                  <i class="ti ti-typography"></i>
                </span>
                <span class="hide-menu">Typography</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">AUTH</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="{% url 'user:login' %}" aria-expanded="false">
                <span>
                  <i class="ti ti-login"></i>
                </span>
                <span class="hide-menu">Login</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./authentication-register.html" aria-expanded="false">
                <span>
                  <i class="ti ti-user-plus"></i>
                </span>
                <span class="hide-menu">Register</span>
              </a>
            </li>
            <li class="nav-small-cap">
              <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
              <span class="hide-menu">EXTRA</span>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./icon-tabler.html" aria-expanded="false">
                <span>
                  <i class="ti ti-mood-happy"></i>
                </span>
                <span class="hide-menu">Icons</span>
              </a>
            </li>
            <li class="sidebar-item">
              <a class="sidebar-link" href="./sample-page.html" aria-expanded="false">
                <span>
                  <i class="ti ti-aperture"></i>
                </span>
                <span class="hide-menu">Sample Page</span>
              </a>
            </li>
          </ul>
          <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
            <div class="d-flex">
              <div class="unlimited-access-title me-3">
                <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                <a href="https://adminmart.com/product/modernize-bootstrap-5-admin-template/" target="_blank" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
              </div>
              <div class="unlimited-access-img">
                <img src="../assets/images/backgrounds/rocket.png" alt="" class="img-fluid">
              </div>
            </div>
          </div> {% endcomment %}
        </nav>
        <!-- End Sidebar navigation -->
      </div>
      <!-- End Sidebar scroll-->
    </aside>
    <!--  Sidebar End -->
    <!--  Main wrapper -->
    <div class="body-wrapper" >
      <!--  Header Start -->
      <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
          <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
              <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                <i class="ti ti-menu-2"></i>
              </a>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                <i class="ti ti-bell-ringing"></i>
                <div class="notification bg-primary rounded-circle"></div>
              </a>
            </li> {% endcomment %}
          </ul>
          <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
              {% block search %}
              {% endblock %}
              <li class="nav-item dropdown">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                  aria-expanded="false">
                  <img src={% static "images/profile/user-1.jpg" %} alt="" width="35" height="35" class="rounded-circle">
                </a>
                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                  <div class="message-body">
                    <a href="{% url "user:logout" %}" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      
      <!--  Header End -->
      
      {% block content %}{% endblock content %}
        {% comment %} <div class="py-6 px-6 text-center">
          <p class="mb-0 fs-4">This is a Footer <a href="#" target="_blank" class="pe-1 text-primary text-decoration-underline">2024 @ Copyright Udaysk</a></p>
        </div> {% endcomment %}
      </div>
    </div>
  </div>
  <script src="{% static "libs/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "libs/bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "js/sidebarmenu.js" %}"></script>
  <script src="{% static "js/app.min.js" %}"></script>
  <script src="{% static "libs/apexcharts/dist/apexcharts.min.js" %}"></script>
  <script src="{% static "libs/simplebar/dist/simplebar.js" %}"></script>
  <script src="{% static "js/dashboard.js" %}"></script>
 
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>


  <script src="{% static 'js/comboTreePlugin.js' %} " type="text/javascript"></script>
  {% block js %}
  {% endblock js %}

</body>

</html>

templates/landing.html
<!DOCTYPE html>

<html lang="en">
  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    <!-- Custom styles -->
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Arial', sans-serif;
            background: url('your-background-image.jpg') center/cover fixed; /* Replace 'your-background-image.jpg' with your image URL */
            filter: blur(5px);
            height: 100vh;
            overflow: hidden;
        }

        .navbar {
            background-color: #fff;
        }

        .navbar-brand {
            font-weight: bold;
        }

        .footer {
            background-color: #333;
            color: #fff;
            padding: 20px 0;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
    </style>
</head>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">DNA Exports</a>
        <div class="ml-auto">
            <a class="btn btn-outline-primary" href="#">Login</a>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container-fluid text-center text-white">
        <div class="row">
            <div class="col-12">
                <h1 class="mt-5">CRM System</h1>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in leo auctor, aliquet turpis eu, sagittis libero. Sed bibendum elit ut justo congue, id tristique nisi tempus.</p>
            </div>
        </div>
    </div>

    <!-- Footer -->
    <div class="footer text-center">
        <p>&copy; 2024 Your Company. All rights reserved.</p>
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>